# Generated by Django 3.0.2 on 2020-01-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(default='anonymous', max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('describe', models.TextField(default='Write')),
            ],
        ),
    ]
